development: 
  adapter: postgresql
  database: readings_dev_prac_1
  pool: 5
  timeout: 5000

test: 
  adapter: postgresql
  database: readings_test_prac_1
  pool: 5
  timout: 5000

production: 
  adapter: postgresql
  database: readings_prod_prac_1
  pool: 5
  timeout: 5000
   